# -*- coding: utf-8 -*-
"""Estadisticas descriptivas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/126lUQI149Q3Ndrw-Q7cvrw-0homW7U_X
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("spotify.csv")

df.shape

df.columns

df.describe()

media = df.mean(numeric_only=True)
mediana = df.median(numeric_only=True)
desviacion = df.std(numeric_only=True)

print("Media:\n", media)
print("\nMediana:\n", mediana)
print("\nDesviación Estándar:\n", desviacion)


#La variable Edad se centra en torno a los 30 años.  La media y la mediana son semejantes, así que no existen valores atípicos importantes.  La desviación estándar es pequeña 2, lo que señala que la mayor parte de las edades se encuentran cerca de la media.
