# -*- coding: utf-8 -*-
"""Mapas de calor y boxplots

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N8KZ9gkOgJIO1d0pLFGbkCI8DBIomv-3
"""

import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv("Facebook_Marketplace_data.csv")

import matplotlib.pyplot as plt
df.hist()
plt.show()

df.boxplot()
plt.title("Diagramas de Caja y Bigotes")
plt.show()

corr = df.corr(numeric_only=True)
plt.imshow(corr)
plt.colorbar()
plt.title("Mapa de calor - Matriz de correlaciones")
plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
plt.yticks(range(len(corr.columns)), corr.columns)
plt.show()